### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by jdzwhy** [uavorg/uavstack#40]
系统：centos6.7

安装包：oneshotstart_linux

日志：http://pan.baidu.com/s/1skPciwH

**Comment by uavstack** [comment]
Hi，
1. 提示一下， 首先日志的uavhm和uavagent是反的。uavagent下的是HM的日志，而uavhm下的是MA的日志。
2. MA应该没有什么问题，no container的异常可以忽略那是http scan扫描.
3. HM没有启动成功，由于以下错误Caused by: java.lang.AbstractMethodError: io.netty.util.concurrent.MultithreadEventExecutorGroup.newChild(Ljava/util/concurrent/Executor;[Ljava/lang/Object;)Lio/netty/util/concurrent/EventExecutor;

这个是HM在启动的时候要启动RocketMQ的consumer，这是RocketMQ内部报的错误~~，这个错误也导致了AppHub的错误Connection[http://localhost:8011/ah/app] is Unavailable。

**很遗憾，我们使用了一个干净的环境，并且版本也是CentOS 6.7，使用oneshotstart_linux，还是未能重现问题（可以正常启动HM）。**
以下是我们系统环境信息:

[root@TA30-30 oneshotstart_linux]# cat /etc/issue
CentOS release 6.7 (Final)
Kernel \r on an \m

[root@TA30-30 oneshotstart_linux]#  cat /proc/version
Linux version 2.6.32-573.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Thu Jul 23 15:44:03 UTC 2015

可以check一下系统是否有很大差距，理论上都是6.7应该是一样的，除非系统被裁决过。

**另一个建议：是否可以更换另外一台机器，安装oneshotstart_linux。看是否会有同样的问题。**

4. 如果还有问题，是否可以把你们机器的OS信息发给我们check一下？

**Comment by uavstack** [comment]
请尝试试用包含PR #46的的安装包，验证问题是否还存在
